/**
 * Enhanced Swimlane Layout Engine
 * Implements complete autofit with mxGraph-style lane resizing and child positioning
 */

import { Node, Edge } from 'reactflow';

export interface SwimlaneLayoutOptions {
  paddingX: number;
  paddingY: number;
  headerHeight: number;
  nodeSpacing: number;
  direction: 'LR' | 'TB' | 'RL' | 'BT';
  autoConnect: boolean; // Feature 2: auto-wire children
}

export interface LayoutResult {
  nodes: Node[];
  edges: Edge[];
  metadata: {
    laneResizes: Array<{
      laneId: string;
      oldBounds: { width: number; height: number };
      newBounds: { width: number; height: number };
    }>;
    autoConnections: Array<{
      id: string;
      source: string;
      target: string;
      type: 'auto-generated';
    }>;
  };
}

export class EnhancedSwimlaneEngine {
  private options: SwimlaneLayoutOptions;

  constructor(options: Partial<SwimlaneLayoutOptions> = {}) {
    this.options = {
      paddingX: 40,
      paddingY: 60,
      headerHeight: 40,
      nodeSpacing: 30,
      direction: 'LR',
      autoConnect: false,
      ...options
    };
  }

  /**
   * Main method: Complete autofit for all swimlanes
   */
  public layoutSwimlanes(nodes: Node[], edges: Edge[]): LayoutResult {
    console.log('🏊 Starting enhanced swimlane layout...');
    
    const laneNodes = nodes.filter(n => n.type === 'lane');
    const processNodes = nodes.filter(n => n.type !== 'lane');
    
    let updatedNodes = [...nodes];
    // Clean up existing auto-generated edges
    let updatedEdges = edges.filter(e => !e.data?.autoGenerated);
    
    const metadata: LayoutResult['metadata'] = {
      laneResizes: [],
      autoConnections: []
    };

    // Process each lane individually
    for (const lane of laneNodes) {
      const result = this.layoutSingleLane(lane, processNodes, updatedEdges);
      
      // Update nodes with new positions
      updatedNodes = updatedNodes.map(n => {
        const updated = result.updatedNodes.find(un => un.id === n.id);
        return updated || n;
      });
      
      // Track lane resize
      metadata.laneResizes.push(result.laneResize);
      
      // Add auto-generated connections if enabled
      if (this.options.autoConnect && result.autoConnections.length > 0) {
        // Remove any existing auto-connections for this lane first
        updatedEdges = updatedEdges.filter(e => 
          !(e.data?.autoGenerated && e.data?.laneId === lane.id)
        );
        updatedEdges = [...updatedEdges, ...result.autoConnections];
        metadata.autoConnections.push(...result.autoConnections.map(edge => ({
          id: edge.id,
          source: edge.source!,
          target: edge.target!,
          type: 'auto-generated' as const
        })));
      }
    }

    // Generate cross-lane connections if auto-connect is enabled
    if (this.options.autoConnect) {
      const crossLaneConnections = this.generateCrossLaneConnections(laneNodes, updatedNodes);
      if (crossLaneConnections.length > 0) {
        updatedEdges = [...updatedEdges, ...crossLaneConnections];
        metadata.autoConnections.push(...crossLaneConnections.map(edge => ({
          id: edge.id,
          source: edge.source!,
          target: edge.target!,
          type: 'auto-generated' as const
        })));
      }
    }

    console.log(`✅ Layout complete. Resized ${metadata.laneResizes.length} lanes, created ${metadata.autoConnections.length} auto-connections`);
    
    return {
      nodes: updatedNodes,
      edges: updatedEdges,
      metadata
    };
  }

  /**
   * Layout a single lane with complete autofit
   */
  private layoutSingleLane(lane: Node, allProcessNodes: Node[], edges: Edge[]) {
    const laneChildren = allProcessNodes.filter(n => 
      this.isNodeInLane(n, lane)
    );

    console.log(`📐 Laying out lane "${lane.data?.label}" with ${laneChildren.length} children`);

    if (laneChildren.length === 0) {
      return {
        updatedNodes: [lane],
        laneResize: {
          laneId: lane.id,
          oldBounds: { width: lane.width || 800, height: lane.height || 200 },
          newBounds: { width: 800, height: 200 }
        },
        autoConnections: []
      };
    }

    // Step 1: Apply hierarchical layout to children
    const layoutedChildren = this.applyHierarchicalLayout(laneChildren, lane);

    // Step 2: Calculate bounding box of all children
    const bounds = this.calculateBoundingBox(layoutedChildren);

    // Step 3: Resize lane to fit children + padding
    const newLaneWidth = Math.max(bounds.width + (this.options.paddingX * 2), 300); // Minimum width
    const newLaneHeight = Math.max(bounds.height + this.options.paddingY + this.options.headerHeight, 150); // Minimum height

    const updatedLane: Node = {
      ...lane,
      width: newLaneWidth,
      height: newLaneHeight,
      style: {
        ...lane.style,
        width: newLaneWidth,
        height: newLaneHeight
      },
      data: {
        ...lane.data,
        width: newLaneWidth,
        height: newLaneHeight
      }
    };

    // Step 4: Generate auto-connections if enabled
    const autoConnections = this.options.autoConnect 
      ? this.generateAutoConnections(layoutedChildren, lane.id)
      : [];

    return {
      updatedNodes: [updatedLane, ...layoutedChildren],
      laneResize: {
        laneId: lane.id,
        oldBounds: { width: lane.width || 800, height: lane.height || 200 },
        newBounds: { width: newLaneWidth, height: newLaneHeight }
      },
      autoConnections
    };
  }

  /**
   * Apply hierarchical layout (left-to-right flow) to lane children
   */
  private applyHierarchicalLayout(children: Node[], lane: Node): Node[] {
    if (children.length === 0) return [];

    // Sort children by their current X position (preserve rough user ordering)
    const sortedChildren = [...children].sort((a, b) => 
      (a.position?.x || 0) - (b.position?.x || 0)
    );

    // Layout in rows/columns based on direction
    const { paddingX, paddingY, headerHeight, nodeSpacing } = this.options;

    return sortedChildren.map((child, index) => {
      let newX: number;
      let newY: number;

      if (this.options.direction === 'LR') {
        // Left-to-right: horizontal flow (relative to lane)
        newX = paddingX + (index * (120 + nodeSpacing)); // Relative positioning
        newY = headerHeight + paddingY;
      } else {
        // Top-to-bottom: vertical flow (relative to lane)
        newX = paddingX;
        newY = headerHeight + paddingY + (index * (60 + nodeSpacing));
      }

      return {
        ...child,
        position: { x: newX, y: newY },
        parentNode: lane.id,
        extent: 'parent' as const,
        data: {
          ...child.data,
          laneId: lane.id
        }
      };
    });
  }

  /**
   * Calculate bounding box of nodes (relative positioning)
   */
  private calculateBoundingBox(nodes: Node[]): { width: number; height: number } {
    if (nodes.length === 0) return { width: 200, height: 100 };

    const positions = nodes.map(n => ({
      x: n.position.x,
      y: n.position.y,
      width: n.width || 120,
      height: n.height || 60
    }));

    const minX = Math.min(...positions.map(p => p.x));
    const maxX = Math.max(...positions.map(p => p.x + p.width));
    const minY = Math.min(...positions.map(p => p.y));
    const maxY = Math.max(...positions.map(p => p.y + p.height));

    return {
      width: Math.max(maxX - minX, 200), // Minimum content width
      height: Math.max(maxY - minY, 80)  // Minimum content height
    };
  }

  /**
   * Feature 2: Generate auto-connections between shapes in a composite/lane
   */
  private generateAutoConnections(children: Node[], laneId: string): Edge[] {
    if (children.length < 2) return [];

    const connections: Edge[] = [];
    
    // Sort by position for sequential connection
    const sorted = [...children].sort((a, b) => {
      if (this.options.direction === 'LR') {
        return a.position.x - b.position.x;
      } else {
        return a.position.y - b.position.y;
      }
    });

    // Create sequential connections: A → B → C → D
    for (let i = 0; i < sorted.length - 1; i++) {
      const source = sorted[i];
      const target = sorted[i + 1];
      
      connections.push({
        id: `auto-${laneId}-${i}`,
        source: source.id,
        target: target.id,
        type: 'smoothstep',
        animated: true,
        style: { 
          stroke: '#10b981', 
          strokeWidth: 2,
          strokeDasharray: '5,5'
        },
        label: 'Auto',
        data: {
          autoGenerated: true,
          laneId: laneId
        }
      });
    }

    console.log(`🔗 Generated ${connections.length} auto-connections for lane ${laneId}`);
    return connections;
  }

  /**
   * Check if a node is inside a specific lane
   */
  private isNodeInLane(node: Node, lane: Node): boolean {
    // Check if node has explicit parent reference
    if (node.parentNode === lane.id) return true;
    
    // Spatial check: is node position inside lane bounds?
    const nodeX = node.position.x;
    const nodeY = node.position.y;
    const laneX = lane.position.x;
    const laneY = lane.position.y;
    const laneWidth = lane.data?.width || lane.width || 800;
    const laneHeight = lane.data?.height || lane.height || 200;

    return (
      nodeX >= laneX &&
      nodeX <= laneX + laneWidth &&
      nodeY >= laneY + (this.options.headerHeight || 40) &&
      nodeY <= laneY + laneHeight
    );
  }

  /**
   * Generate cross-lane connections (handoffs between swimlanes)
   */
  private generateCrossLaneConnections(lanes: Node[], allNodes: Node[]): Edge[] {
    const connections: Edge[] = [];
    const sortedLanes = [...lanes].sort((a, b) => a.position.y - b.position.y);
    
    for (let i = 0; i < sortedLanes.length - 1; i++) {
      const currentLane = sortedLanes[i];
      const nextLane = sortedLanes[i + 1];
      
      // Find last node in current lane
      const currentLaneNodes = allNodes.filter(n => 
        n.parentNode === currentLane.id || this.isNodeInLane(n, currentLane)
      ).sort((a, b) => a.position.x - b.position.x);
      
      // Find first node in next lane
      const nextLaneNodes = allNodes.filter(n => 
        n.parentNode === nextLane.id || this.isNodeInLane(n, nextLane)
      ).sort((a, b) => a.position.x - b.position.x);
      
      if (currentLaneNodes.length > 0 && nextLaneNodes.length > 0) {
        const lastNode = currentLaneNodes[currentLaneNodes.length - 1];
        const firstNode = nextLaneNodes[0];
        
        connections.push({
          id: `cross-lane-${i}`,
          source: lastNode.id,
          target: firstNode.id,
          type: 'smoothstep',
          animated: true,
          style: { 
            stroke: '#7b1fa2', 
            strokeWidth: 2,
            strokeDasharray: '8,4'
          },
          label: 'Handoff',
          data: {
            autoGenerated: true,
            crossLane: true,
            fromLane: currentLane.id,
            toLane: nextLane.id
          }
        });
      }
    }
    
    console.log(`🔗 Generated ${connections.length} cross-lane connections`);
    return connections;
  }

  /**
   * Update layout options
   */
  public updateOptions(options: Partial<SwimlaneLayoutOptions>): void {
    this.options = { ...this.options, ...options };
  }
}

// Singleton instance
export const enhancedSwimlaneEngine = new EnhancedSwimlaneEngine();